OctopusDeploy/octopus-jenkins-plugin

pom.xml, src/main/java/com/octopusdeploy/api/DeploymentsApi.java, src/main/java/com/octopusdeploy/api/data/SelectedPackage.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
PR  #12 from cjuroz/new-feature
=> merge feature enhancement 

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
=> Build Summary - Fixed an overly aggressive slash-truncation 

src/main/java/com/octopusdeploy/api/AuthenticatedWebClient.java, src/main/java/com/octopusdeploy/api/ChannelsApi.java, src/main/java/com/octopusdeploy/api/DeploymentsApi.java, src/main/java/com/octopusdeploy/api/EnvironmentsApi.java, src/main/java/com/octopusdeploy/api/OctopusApi.java, src/main/java/com/octopusdeploy/api/ProjectsApi.java, src/main/java/com/octopusdeploy/api/ReleasesApi.java, src/main/java/com/octopusdeploy/api/SpacesApi.java, src/main/java/com/octopusdeploy/api/TasksApi.java, src/main/java/com/octopusdeploy/api/TenantsApi.java, src/main/java/com/octopusdeploy/api/VariablesApi.java, src/main/java/com/octopusdeploy/api/data/Space.java, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPlugin.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusValidator.java, src/main/java/hudson/plugins/octopusdeploy/constants/OctoConstants.java, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-spaceId.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/help-spaceId.html
This PR builds on top of #29 so should not be merged before that PR has been merged.
=> Add support for spaces

src/main/java/com/octopusdeploy/api/ChannelsApi.java, src/main/java/com/octopusdeploy/api/EnvironmentsApi.java, src/main/java/com/octopusdeploy/api/ProjectsApi.java, src/main/java/com/octopusdeploy/api/SpacesApi.java, src/main/java/com/octopusdeploy/api/TenantsApi.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java, src/main/resources/hudson/plugins/octopusdeploy/OctoInstallation/global.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctoInstallation/help-home.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-serverId.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/help-serverId.html
This PR builds upon #30 so should not be merged before that is merged.
=> UI enhancements

src/main/java/com/octopusdeploy/api/OctopusApi.java, src/main/java/com/octopusdeploy/api/TagSetsApi.java, src/main/java/com/octopusdeploy/api/data/Tag.java, src/main/java/com/octopusdeploy/api/data/TagSet.java, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployServer.java, src/main/java/hudson/plugins/octopusdeploy/utils/Lazy.java, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-additionalArgs.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-cancelOnTimeout.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-deploymentTimeout.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-variables.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/help-additionalArgs.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/help-cancelOnTimeout.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/help-deploymentTimeout.html
This PR builds upon #31 so should not be merged before that PR
=> Add configuration for tenant tags, deployment timeout and additional args for octo.exe

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusValidator.java, src/main/java/hudson/plugins/octopusdeploy/constants/OctoConstants.java, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/global.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-additionalArgs.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-includePaths.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-outputPath.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-overwriteExisting.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-packageFormat.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-packageId.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-packageVersion.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-sourcePath.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-toolId.html, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/help-verboseLogging.html
=> Add new step to package application

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPlugin.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusValidator.java
JavaDoc parameters are required to match method parameters for the project to build.  Added missing parameters.
=> Add missing javadoc

pom.xml, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java
=> Update parent POM and minimum Jenkins version

src/main/java/com/octopusdeploy/api/data/Project.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPlugin.java, src/main/java/hudson/plugins/octopusdeploy/OctopusValidator.java, src/main/resources/hudson/plugins/octopusdeploy/BuildInfoSummary/badge.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctoInstallation/global.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPlugin/global.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly, src/main/resources/index.jelly
OctopusDeploy -> Octopus Deploy in UI elements
=> put spaces in betwen OctopusDeploy in UI elements, and more consistency

src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly
I tried to reference a single style sheet, but according to this person
https://stackoverflow.com/a/15567380
it's no longer supported
this is at least only at the top of the 5 components
=> override styles so the section headings look reasonable

src/main/java/com/octopusdeploy/api/DeploymentsApi.java, src/main/java/com/octopusdeploy/api/ReleasesApi.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
This PR adds the links back to the build output and build page as a badge.
These links should exist for either a release creation action or a deploy release action.
=> Query the Octopus API to get links to deployments and release pages

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java, src/main/java/hudson/plugins/octopusdeploy/services/impl/FileServiceImpl.java
Fixes https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/72
=> fixed cli paths for pushing packages

pom.xml, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderBuildStep.java, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
Docs PR: https://github.com/OctopusDeploy/docs/pull/783
The command/aliases for the existing 5 steps are:
`octopusPack`
`octopusPushPackage`
`octopusPushBuildInformation`
`octopusCreateRelease`
`octopusDeployRelease`
Review commit by commit will be the easiest.
=> Add Pipeline support

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderBuildStep.java, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusValidator.java, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly, src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly
These were selects/dropdowns before which didn't allow you to bind these to variables.
I've made them comboxes now, and updated the validation messages to be more intuitive
=> Make Project, Environment and Channel dropdowns comboboxes

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderBuildStep.java, src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java, src/main/java/hudson/plugins/octopusdeploy/OctoInstallation.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPlugin.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java, src/main/java/hudson/plugins/octopusdeploy/exception/ServerConfigurationNotFoundException.java, src/main/java/hudson/plugins/octopusdeploy/utils/JenkinsHelpers.java
Before: 
After:
This primarily came down the `ex.getMessage()` not always returning a valid value.
=> Exception messages were not rendering well

src/main/java/hudson/plugins/octopusdeploy/OctopusBuildInformation.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java, src/main/java/hudson/plugins/octopusdeploy/services/OctopusBuildInformationBuilder.java
Fixes: https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/93
=> Add branch information to build information

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPlugin.java
Fix the maximum length of an API key when configuring Octopus Deploy plugin.
[Trello Card](https://trello.com/c/6E5v5VdO/4132-api-keys-are-too-long-for-azure-devops)
[PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/7611) to extend the API key length in Octopus Server
Quality :heavy_check_mark:
- For changes to the execution pipeline: [`#topic-execution`](https://octopusdeploy.slack.com/archives/C3KT1DFSM)
- For other changes, consider the other `#topic-...` channels
=> Fix API key max length validation

src/test/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorderDescriptorImplTest.java
- Add unit tests for OctopusDeployPushRecorderDescriptorImplTest.DescriptorImpl
=> PushRecorder Descriptor test coverage

build.gradle, pom.xml, src/integration-test/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorderDescriptorImplITest.java, src/integration-test/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorderDescriptorImplITest.java, src/test/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorderDescriptorImplTest.java, src/test/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorderDescriptorImplTest.java, src/test/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorderDescriptorImplTest.java
Test coverage for each recorder descriptor
=> Finalise recorder descriptor test coverage

src/test/java/hudson/plugins/octopusdeploy/BuildInfoSummaryTest.java, src/test/java/hudson/plugins/octopusdeploy/EnvironmentVariableValueInjectorTest.java, src/test/java/hudson/plugins/octopusdeploy/OverwriteModesTest.java, src/test/java/hudson/plugins/octopusdeploy/exception/ServerConfigurationNotFoundExceptionTest.java
Add the last of the uniting testing required for basic coverage
=> Increase unit testing

.github/workflows/main.yml, build.gradle, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java, src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
=> fix!: throw exception, update build
