OctopusDeploy/octopus-jenkins-plugin

src/main/java/com/octopusdeploy/api/DeploymentProcess.java
src/main/java/com/octopusdeploy/api/DeploymentProcessStep.java
src/main/java/com/octopusdeploy/api/DeploymentProcessStepAction.java
src/main/java/com/octopusdeploy/api/DeploymentProcessTemplate.java
src/main/java/com/octopusdeploy/api/Environment.java
src/main/java/com/octopusdeploy/api/ErrorParser.java
src/main/java/com/octopusdeploy/api/OctopusApi.java
src/main/java/com/octopusdeploy/api/Project.java
src/main/java/com/octopusdeploy/api/Release.java
src/main/java/com/octopusdeploy/api/SelectedPackage.java
src/main/java/com/octopusdeploy/api/Task.java
src/main/java/com/octopusdeploy/api/Variable.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-variables.html

https://github.com/vistaprint/octopus-jenkins-plugin/issues/5
* Added a text area to put the properties to pass along
* Added Variable API object
* Added logic to merge interface values and default values from Octopus 
Used .../OctopusDeploy-Api/wiki/DeploymentPreviews to get current set of variables to pass to deployment, and .../OctopusDeploy-Api/wiki/Deployments to figure out the need to pass FormValues with the variables defined as "[guid]": "value"
This is probably the begining since for now I am assuming all variable are strings.

Allow passing in of variables to octopus deployment

---

src/main/java/com/octopusdeploy/api/DeploymentsApi.java
src/main/java/com/octopusdeploy/api/ReleasesApi.java
src/main/java/com/octopusdeploy/api/data/SelectedPackage.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
src/main/java/hudson/plugins/octopusdeploy/PackageConfiguration.java
src/main/resources/hudson/plugins/octopusdeploy/PackageConfiguration/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/PackageConfiguration/help-packageName.html
src/main/resources/hudson/plugins/octopusdeploy/PackageConfiguration/help-packageReferenceName.html

This update is to incorporate the API changes that were made to Octopus server's API in `2018.8`.
The API change requires passing of the logical "reference name" for the package on the step, now that there can be multiple packages per step.
Have tested against an Octopus 2018.9 server, using configurations with and without the package references.
Fixes https://github.com/vistaprint/octopus-jenkins-plugin/issues/24

Updates to package referencing within steps

---

.gitignore
pom.xml
src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctoInstallation.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPlugin.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployServer.java
src/main/java/hudson/plugins/octopusdeploy/constants/OctoConstants.java
src/main/resources/hudson/plugins/octopusdeploy/OctoInstallation/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctoInstallation/global.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/help-toolId.html
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPlugin/global.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/help-toolId.html

Also includes some minor changes to server and step configurations: 
- Store API Key as a `secret` instead of plain-text https://github.com/OctopusDeploy/octopus-jenkins-plugin/commit/c087af46b69f32ce8ceeb0bd7a0216f1cb5af577
- Add verbose logging to steps https://github.com/OctopusDeploy/octopus-jenkins-plugin/commit/a16592727b34a65510149e466342b961b4d1da4a
- Add ignore ssl errors to Octopus connection https://github.com/OctopusDeploy/octopus-jenkins-plugin/commit/2631678e9e1f93c013fb93c1e2b5aff16479bde8

Refactor plugin to use octo.exe instead of the API to create/deploy releases

---

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly

there's no way I could see to have an advanced component, so it's just some conditional decision based on whether any advanced options are set. The penalty is the repated jelly code.
I tried to wrap the `<f:advanced>` and `</f:advanced>` in the `<j:choose>` & `<j:when>` without any luck. It would throw an about lacking the closing `</f:advanced>`.

Advanced options are a Jelly concept

---

pom.xml

The Jenkins plugin search for "octopus" or "deploy" does not find the Octopus plugin. Only "OctopusDeploy" yields a result. Introducing a space in the plugin name for better searchability and removing the redundant "plugin" word in accordance with style guidelines: https://jenkins.io/doc/developer/publishing/style-guides/
Plugins are keyed on `artifactId`, so the name change should still refer to the same plugin.

Rename the plugin to 'Octopus Deploy' for better search discoverability

---

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorder.java

Manual testing, of these worked.
This change needs to ship with the new changes because if they are in the "Post Build" section.
And then this change comes into place, a save of the project will clobber existing ones, as they are not of the right type.

make these build steps, not post-build

---

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderBuildStep.java
src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuild.java
src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusValidator.java
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder/config.jelly
src/main/resources/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder/config.jelly

Builder -> Build Step (can have many)
- Package Application
- Push build information
- Push Packages
and
Recorder -> PostBuild for the 2 existing post build actions
- Create Release
- Deploy Release
With this quick change we have, the 3 new steps repeatable:
And the existing steps, still supported **without breaking them**
TODO:

Duplication of AbstractOctopusDeployRecorder to support 2 step types

---

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderBuildStep.java
src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java
src/main/java/hudson/plugins/octopusdeploy/OctoInstallation.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployDeploymentRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPackRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java
src/main/java/hudson/plugins/octopusdeploy/services/FileService.java
src/main/java/hudson/plugins/octopusdeploy/services/impl/FileServiceImpl.java

This PR allows the plugin to consider the per-node tool path override value for resolving the `octo` path.
Also changes file resolution for the `push` step to work for slave nodes.
Source: https://secure.helpscout.net/conversation/1133185955/62148?folderId=557082
Sample log entries:
Push command on a Linux host:
```
[build] $ /home/parallels/.dotnet/tools/dotnet-octo push --server https://ben-test.testoctopus.app --apiKey ******** --package test1.39.zip --package test1.40.zip
```
Create release command, Linux host:
```
[build] $ /home/parallels/.dotnet/tools/dotnet-octo create-release --version 41 --channel Default --releaseNotes "Release created by Build [build #41](http://localhost:8080/jenkins/job/build/41/)" --project 1 --server https://ben-test.testoctopus.app --apiKey ******** …
```

fixed tool and fs resolution for nodes

---

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorder.java
src/main/java/hudson/plugins/octopusdeploy/services/OctopusBuildInformationWriter.java

Fixes: https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/69
Before:
```
ERROR: Error writing c:\jenkins\workspace\_Misc\AgentAdmin_Test_OctoPlugin\octopus.buildinfo file
FATAL: Failed to push the build information: c:\jenkins\workspace\_Misc\AgentAdmin_Test_OctoPlugin\octopus.buildinfo (The system cannot find the path specified)
```
After from Linux master:
```
Building on master in workspace /home/parallels/git/octopus-jenkins-plugin/work/workspace/octo-push-build-info
INFO: Creating octopus.buildinfo in /home/parallels/git/octopus-jenkins-plugin/work/workspace/octo-push-build-info
```
from Windows slave:
```
Building remotely on windows in workspace c:\Jenkins\workspace\octo-push-build-info
INFO: Creating octopus.buildinfo in c:\Jenkins\workspace\octo-push-build-info
```

Handle executing the push build info step on a slave

---

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java

Reading a .txt fails with no error message, only a <Error Reading Files> is added to the release notes.
It should preferably log the actual IOExecption as it makes it easier to debug why it was not able to read the file.

Fixes #64 Log error message if unable to read the release notes file

---

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployPushRecorder.java
src/main/java/hudson/plugins/octopusdeploy/services/FileService.java
src/main/java/hudson/plugins/octopusdeploy/services/impl/FileServiceImpl.java

Checks if the pattern is a full file path by seeing if the file exists before trying to use it as an ant glob. 
Fixes: https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/74

Fixes #74 - Check file path from pattern before using it as ant glob

---

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderBuildStep.java
src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java

Octo is x-plat now, so removing references to `.exe` and making this lowercase

Remove references to Octo.exe

---

src/main/java/hudson/plugins/octopusdeploy/OctoInstallation.java

The validation of the Octopus CLI incorrectly attempts to find a directory instead of a file. This is because the `doCheckHome()` method had the wrong signature, and so the default validation from `hudson.tools.ToolDescriptor.doCheckHome()` was being called.
This PR fixes up the validation so the expected method is called.
Internal link: https://trello.com/c/acEKN8Ls/3505-jenkins-plugin-has-misleading-warning-message-about-location-of-octo-binary

Fixed the validation of the CLI path

---

src/main/java/hudson/plugins/octopusdeploy/AbstractOctopusDeployRecorderPostBuildStep.java
src/main/java/hudson/plugins/octopusdeploy/OctopusDeployReleaseRecorder.java

`AdditionalArgument` field is missing for `Octopus Deploy Release` step.
Unable to set `AdditionalArgument` field to the step.

Fix missing additional args field for deploying a deployment step

---

src/test/java/hudson/plugins/octopusdeploy/OctopusDeployPushBuildInformationRecorderDescriptorImplTest.java

- Added unit test coverage for OctopusDeployPushBuildInformationRecorder.DescriptorImpl

BuildInformationRecorder Descriptor test coverage

---

settings.gradle

Update to latest SDK version with Log4j version increase to address against Dec2021 0-Day RCE
**N.B:** As the Jenkins plugin has not been released since addition of the Java Client, there is no need for the plugin to be released at present with regards to the Dec2021 Log4J 0-Day RCE.

Update Java Client (SDK)

---

src/main/java/hudson/plugins/octopusdeploy/OctopusDeployServer.java

The `id` property will not be written back to XML when data is saved, it will be saved as the new `serverId` field

fix: Add back id property as transient so config files from pre-3.1.7 can be read

---

settings.gradle

This is a regression as we shipped a new version of the plugin after moving from Maven to Gradle and our Gradle file referenced an out-of-date version of our Java SDK client.
Fixes #142

Update our Java SDK to latest version which includes fixes for a log4j vulnerability

---

.github/workflows/main.yml
build.gradle
settings.gradle
src/integration-test/java/com/octopus/helper/BaseIntegrationTest.java
src/test/java/hudson/plugins/octopusdeploy/E2eTest.java

- Updates `org.jenkins-ci.jpi` from 0.43.0 to 0.46.0
- 0.43.0 was referencing `org.jvnet.localizer:maven-localizer-plugin:1.24 `which would not be found
- Updates `Jenkins Plugin` from 2.401.1 to 2.462.3
- 2.462.3 is the last version that supports java 11 and includes the snakeyaml security updates
- Updates `Build and Test` Github Action to run docker containers for the db and server for testing
- Updates `Build and Test` Github Action to remove deprecated use of `set-output` and `actions/upload-artifact@v3`
- Updates `BaseIntegrationTest.java` to include the required SpaceManagersTeams
Fixes https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/156
[sc-100561]
`INTEGRATIONS_FNM_BOT_TOKEN` may need to be updated for release please to run.

fix: update github workflow and upgrade jenkins plugin

---

build.gradle

Fixes https://github.com/OctopusDeploy/octopus-jenkins-plugin/issues/156
Upon further investigation it was found that snakeyaml 1.26 is brought in by the octopus-sdk dependency.
As the octopus-sdk is only used for testing, we have removed this dependency from the runtime dependencies.
Customer ran:
`ls /pipeline/builds/jenkins/plugins/octopusdeploy/WEB-INF/lib | grep snake`
Returned:
`snakeyaml-1.26.jar`
Local Testing:
1. Built package locally 
`./gradlew clean assemble `
3. Unpacked package 
`mkdir unpacked`
`unzip build/libs/octopusdeploy.hpi -d unpacked`
4. Checked for snakeyaml
`ls unpacked/WEB-INF/lib | grep snake`
5. Nothing was returned
[sc-100561]

fix: remove octopus bundle from runtime dependencies
